# Generated by Django 4.2.7 on 2024-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potfolio', '0004_rename_name_about_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='v_c',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='v_status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
