# Generated by Django 4.2.7 on 2024-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potfolio', '0005_about_v_c_about_v_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
