# Generated by Django 4.2.7 on 2024-01-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potfolio', '0007_remove_about_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
